### ISSUE TITLE
about data preprocessing

### ISSUE THREAD

**Issue by HX-idiot** [siddsax/XML-CNN#1]
Hello, I want to run XML-CNN on several benchmark, but i don't know how to deal with data, can you provide the script you use for  data preprocessing in WIKI31K , AMAZON and others, and the downloading source of dataset?
Thanks~

**Comment by siddsax** [comment]
Hi, I had contacted the authors for the processed data which they shared with me with the following link. Although hyper parameter tuning will be required
for the them which I haven't tried aggressively.

https://drive.google.com/drive/folders/1KQMBZgACUm-ZZcSrQpDPlB6CFKvf9Gfb

**Comment by HX-idiot** [comment]
Thanks a lot. Really appreciate your help.
